import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;

public class MedicalCertificatePDF {

    public static void generateCertificate(String dest,
                                           String studentName,
                                           String activity,
                                           String status,
                                           String remarks,
                                           String bp,
                                           String temp,
                                           String pulse,
                                           String resp,
                                           String certCode,
                                           String nurseName,
                                           String date) throws Exception {
        Document doc = new Document();
        PdfWriter.getInstance(doc, new FileOutputStream(dest));
        doc.open();

        // Header
//        doc.add(new Paragraph("Republic of the Philippines", FontFactory.getFont(FontFactory.HELVETICA, 12)));
//        doc.add(new Paragraph("SOUTHERN LUZON STATE UNIVERSITY", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12)));
//        doc.add(new Paragraph("Lucban, Quezon\n\n", FontFactory.getFont(FontFactory.HELVETICA, 12)));
//        doc.add(new Paragraph("Health Services\n\n\n", FontFactory.getFont(FontFactory.HELVETICA, 12)));

        Paragraph head = new Paragraph("Republic of the Philippines\nSOUTHERN LUZON STATE UNIVERSITY\n"
                + "Lucban, Quezon\n\nHealth Services\n\n\n", FontFactory.getFont(FontFactory.HELVETICA, 12));
        head.setAlignment(Element.ALIGN_CENTER);
        doc.add(head);
        
        Paragraph title = new Paragraph("MEDICAL CERTIFICATE\n\n\n", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14));
        title.setAlignment(Element.ALIGN_CENTER);
        doc.add(title);
        doc.add(new Paragraph("\nDate: " + date + "\n\n\n"));

        // Body
        String body = String.format(
            "To Whom It May Concern:\n\nThis is to certify that Mr./Ms. %s of "
            + "Southern Luzon State University, is Physically and Mentally %s for: %s.\n\n",
            studentName, status.toUpperCase(), activity
        );
        doc.add(new Paragraph(body));

        // Remarks
        doc.add(new Paragraph("\n\nRemarks: " + (remarks != null ? remarks : "N/A") + "\n\n"));

        // Vitals
        doc.add(new Paragraph("\n\nVital Signs: BP: " + bp + "  Temp: " + temp +
                " °C  Pulse: " + pulse + " bpm  Resp: " + resp + " cpm\n\n\n\n"));

        // Signature
        Paragraph sig = new Paragraph("______________________________\n" + nurseName + ", RN\nDirector, University Health Services");
        sig.setAlignment(Element.ALIGN_RIGHT);
        doc.add(sig);

        // Footer
        Paragraph footer = new Paragraph("\n\n\n*Generated by School Clinic System | Certificate ID: " + certCode + "*",
                FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9));
        footer.setAlignment(Element.ALIGN_CENTER);
        doc.add(footer);

        doc.close();
    }
}
